import crypto from 'node:crypto';

export type UploadManifestEntry = {
  objectKey: string;
  sourcePath: string;
  sizeBytes: number;
  sha256: string;
  status: 'pending' | 'already-migrated' | 'mismatch' | 'failed' | 'migrated';
  error?: string;
};

export type UploadManifest = {
  generatedAt: string;
  sourceDir: string;
  apply: boolean;
  entries: UploadManifestEntry[];
  summary: Record<string, number>;
  reconciliation?: {
    fileCount: number;
    totalBytes: number;
    manifestSha256: string;
    completeScan: boolean;
  };
};

export type UploadManifestReconciliation = NonNullable<UploadManifest['reconciliation']>;

/**
 * Creates a stable digest from object key, byte count, and per-file SHA-256.
 * Sorting makes manifests generated by different directory traversal orders
 * comparable without exposing file contents.
 */
export function summarizeUploadEntries(
  entries: Array<Pick<UploadManifestEntry, 'objectKey' | 'sizeBytes' | 'sha256'>>,
  completeScan = true,
): UploadManifestReconciliation {
  const sorted = [...entries].sort((left, right) => left.objectKey.localeCompare(right.objectKey));
  const digest = crypto.createHash('sha256');
  let totalBytes = 0;
  for (const entry of sorted) {
    totalBytes += entry.sizeBytes;
    digest.update(`${entry.objectKey}\0${entry.sizeBytes}\0${entry.sha256}\n`);
  }
  return {
    fileCount: sorted.length,
    totalBytes,
    manifestSha256: digest.digest('hex'),
    completeScan,
  };
}
